### ISSUE TITLE
Problem on 2.4.7 version

### ISSUE THREAD

**Issue by soRailicious** [sewpafly/post-thumbnail-editor#125]
> "Hello,
> 
> Since I updated WordPress to the 4.5 version and then Post Thumbnail Editor to the 2.4.7 version, the latest doesn't work anymore.
> 
> In other words, instead of showing the usual interface of the plugin, I just can see its HTML page. Do you know why?
> 
> Please resolve it quickly because I need it to write every article.
> 
> Thanks!
> 
> https://wordpress.org/plugins/post-thumbnail-editor/"

Hi all,

i've got the same problem... The Sourcecode is between
"pre" tags... Well used for showing sourcecode... I think the developer forget to remove this "debug styled output"...

Via Media Library its still working, but not the solution!

Please help as soon as possible...

https://wordpress.org/support/topic/problem-on-247-version?replies=4

**Comment by jamesfacts** [comment]
I'm experiencing the same issue with 2.4.7—instead of the interface I see raw HTML. Please keep us posted!
<img width="1162" alt="screenshot 2016-04-22 14 15 44" src="https://cloud.githubusercontent.com/assets/3483691/14751013/d136211a-0895-11e6-84e3-2e4bfb044d1f.png">

**Comment by sewpafly** [comment]
2.4.8 should have the fix

**Comment by jamesfacts** [comment]
Thanks very much!
