### ISSUE TITLE
AWS and Wordpress 3.8

### ISSUE THREAD

**Issue by lukeshumard** [sewpafly/post-thumbnail-editor#84]
I'm using Amazon S3 with Cloudfront (https://github.com/bradt/wp-tantan-s3) with Post Thumbnail Editor, which was working great until I updated to Wordpress 3.8. Now I'm getting 403 errors whenever I try and re-crop an image. What gets returned is...
`GET http://xxxxxxxxxx-1000x548.jpg?c22e 403 (Forbidden) load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils&ver=3.8:4`

...where `xxxxxxxxxx` is the path to my image, and with the cropped size. However, the new image is never uploaded to S3. The original version is still there.

Any idea why this might be happening?

**Comment by tiefenb** [comment]
Hi,

so what was the solution?

**Comment by tiefenb** [comment]
I have the Problem with Amazon S3 Plugin while saving:

[DEBUG  ][2015-10-22T13:48:38+00:00][ PARAMETERS: Array
(
    [action] => pte_ajax
    [id] => 29535
    [pte-action] => confirm-images
    [pte-confirm] => Array
        (
            [preview-wide] => IMG_7446-1520x424-1445521709.jpg
        )

    [pte-nonce] => f245f3ce37
) ]
[DEBUG  ][2015-10-22T13:48:38+00:00][ pte_get_all_alternate_size_information returned: Array
(
    [preview-wide] => Array
        (
            [width] => 1520
            [height] => 424
            [crop] => 1
            [current] => Array
                (
                    [file] => IMG_7446-1520x4241.jpg
                    [width] => 
                    [height] => 
                    [path] => 2015/10/IMG_7446-1520x4241.jpg
                    [url] => https://files.derbrutkasten.at/2015/10/IMG_7446-1520x4241.jpg
                )

        )

) ]
[DEBUG  ][2015-10-22T13:48:38+00:00][ Deleting old thumbnail: https://files.derbrutkasten.at/2015/10/IMG_7446-1520x4241.jpg ]
[DEBUG  ][2015-10-22T13:48:38+00:00][ Moving '/Applications/MAMP/htdocs/derbrutkasten/public/wp-content/uploads/ptetmp/29535/IMG_7446-1520x424-1445521709.jpg' to 'https://files.derbrutkasten.at/2015/10/IMG_7446-1520x424-1445521709.jpg' ]
[DEBUG  ][2015-10-22T13:48:39+00:00][ Updating 'preview-wide' metadata: Array
(
    [file] => IMG_7446-1520x424-1445521709.jpg
    [width] => 
    [height] => 
) ]
[WARNUNG][2015-10-22T13:48:39+00:00][ Buffered output: <br />
<b>Warning</b>:  rename(): Cannot rename a file across wrapper types in <b>/Applications/MAMP/htdocs/derbrutkasten/public/wp-content/plugins/post-thumbnail-editor/php/functions.php</b> on line <b>614</b><br /> ]

**Comment by AsafAzoulay** [comment]
what i need to do for fix this bug?
